"""add visitor_logs table

Revision ID: 8b1993d8943b
Revises: fdd6fb49910b
Create Date: 2025-06-01 18:26:42.991022

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8b1993d8943b"
down_revision: Union[str, None] = "fdd6fb49910b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "visitor_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("visitor_dbid", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["visitor_dbid"], ["visitors.dbid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_visitor_logs_id"), "visitor_logs", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_visitor_logs_id"), table_name="visitor_logs")
    op.drop_table("visitor_logs")
    # ### end Alembic commands ###
